*          DATA SET GAHNG03    AT LEVEL 002 AS OF 08/22/00                      
*PHASE TB0503A                                                                  
         TITLE 'HANGMAN GAME - DICTIONARY PART 3'                               
HANGMAN3 CSECT                                                                  
         DC    C'NONSENSE NOON NORTH NOSTALGIA NOTABLE NOTCH N'                 
         DC    C'OTHING NOTORIOUS NUANCE NUGGET NUMERICAL NUTR'                 
         DC    C'ITION OBEDIENCE OBJECTIVE OBLITERATE OBSCENE '                 
         DC    C'OBSERVER OCCASION OCEAN OCTAVE OFFENSIVE OFFI'                 
         DC    C'CE OFTEN OINTMENT OMINOUS OMITTED ONLOOKER OP'                 
         DC    C'AQUE OPERATE OPINION OPULENT ORBIT ORCHESTRA '                 
         DC    C'ORDINARY ORGANIC ORNAMENT ORPHAN OSTRICH OUTC'                 
         DC    C'OME OUTLINE OUTRAGEOUS OVATION OVERACT OVERDR'                 
         DC    C'AFT OVERGROWN OVERSHADOW OVERTURE OVERWHELM O'                 
         DC    C'WNERSHIP OXIDIZE PACIFIST PAINFUL PALATIAL PA'                 
         DC    C'LINDROME PALLIATIVE PAMPHLET PANORAMA PANTOMI'                 
         DC    C'NE PARADOX PARELLEL PARASITE PARENT PARSIMONY'                 
         DC    C' PARTIAL PARTITION PASSAGE PASSION PASSPORT P'                 
         DC    C'ASTEL PASTORAL PATHETIC PAUPER PAVEMENT PAYME'                 
         DC    C'NT PEACEFUL PECULIAR PEDANTIC PENALTY PENCHAN'                 
         DC    C'T PENETRATE PENNANT PERCENTAGE PERENNIAL PERF'                 
         DC    C'ORM PERISCOPE PERJURY PERPLEX PERSONALITY PER'                 
         DC    C'VERSE PETITION PETROLEUM PHANTOM PHONETIC PHY'                 
         DC    C'SIOLOGY PICKPOCKET PICTURESQUE PIGMENT PILGRI'                 
         DC    C'M PILLOW PINCH PINNACLE PIQUANT PISTON PITIFU'                 
         DC    C'L PLACARD PLAGIARIST PLAINTIVE PLATEAU PLATIN'                 
         DC    C'UM PLAYGROUND PLEASANT PLETHORA PLINTH PLUMME'                 
         DC    C'T PNEUMATIC POIGNANT POISONOUS POLARITY POLIT'                 
         DC    C'ICIAN POLYGAMY POMPOUS PONDEROUS POPULATION P'                 
         DC    C'ORTFOLIO POSITIVE POSSESSION POSTERITY POSTUL'                 
         DC    C'ATE POTTERY POUND POWERFUL PRACTICE PRECAUTIO'                 
         DC    C'N PRECIOUS PRECISE PREDICTION PREGNANT PREMIU'                 
         DC    C'M PREPARE PRESCRIBE PRESIDENT PRESSURE PRETEX'                 
         DC    C'T PREVAIL PREVIOUS PRICELESS PRIMARY PRINCIPL'                 
         DC    C'E PRISM PRIVILEGE PROCEDURE PROCRASTINATE PRO'                 
         DC    C'DUCTION PROFICIENT PROFIT PROJECTILE PROMOTIO'                 
         DC    C'N PROMPTER PROPAGANDA PROPITIOUS PROPORTION P'                 
         DC    C'ROSECUTE PROSPECTUS PROTEIN PROVERB PROVINCIA'                 
         DC    C'L PROXIMITY PSEUDONYM PUBERTY PUBLICATION PUL'                 
         DC    C'SATION PUNCH PUNCTUAL PURCHASE PURIST PURPOSE'                 
         DC    C' PURVEY PUSHING PUZZLE PYROMANIAC QUANTITY QU'                 
         DC    C'ARTERS QUENCH QUESTION QUOTA RACEHORSE RACONT'                 
         DC    C'EUR RADIATION RAILWAY RAINCOAT RAMPANT RANDOM'                 
         DC    C' RANGER RANSOM RATIONAL RAVENOUS REACTION REA'                 
         DC    C'DERSHIP REALISTIC REASON REBIRTH RECEIPT RECE'                 
         DC    C'SSION RECIPROCAL RECONCILE RECORD RECRUIT REC'                 
         DC    C'TANGLE REDUNDANT REFERENDUM REFRACTION REFUSA'                 
         DC    C'L REGIMENT REGRESSION REINFORCE RELATION RELE'                 
         DC    C'VANT RELIGIOUS REMAINDER REMORSE RENAISSANCE '                 
         DC    C'RENDEZVOUS REORGANIZE REPERTOIRE REPRESENTATI'                 
         DC    C'ON REPRISAL REPUBLICAN REQUEST RESERVATION RE'                 
         DC    C'SIGNATION RESONANT RESPONSIBLE RESTAURANT RES'                 
         DC    C'TRICT RETALIATE REUNION REVEILLE REVISION REV'                 
         DC    C'OLUTION RHINOCEROS RICOCHET RIDICULOUS RIFLEM'                 
         DC    C'AN RIGOROUS RIOTOUS RITUAL ROBBERY ROCKET ROG'                 
         DC    C'UE ROMANTIC ROTATION ROUGHNESS ROULETTE ROUTI'                 
         DC    C'NE RUDIMENT RUINOUS RUNAWAY RUSTIC RUTHLESS S'                 
         DC    C'ABOTAGE SACRIFICE SADNESS SALESMAN SANCTION S'                 
         DC    C'ARCASM SATELLITE SATISFACTORY SAVOURY SCAFFOL'                 
         DC    C'D SCALPEL SCARCELY SCENERY SCHOLAR SCIENTIFIC'                 
         DC    C' SCISSORS SCORPION SCRAMBLE SCREWDRIVER SCRIB'                 
         DC    C'BLE SCULPTURE SEAMANSHIP SEARCHLIGHT SECLUSIO'                 
         DC    C'N SECONDARY SECRETARY SEDIMENT SEDUCTION SEGM'                 
         DC    C'ENT SELECTION SEMBLANCE SEMITONE SENATOR SENS'                 
         DC    C'ATION SENSUAL SERENADE SERIOUS SERVE BKEND   '                 
**PAN#1  CSECT                                                                  
**PAN#1  DC    CL21'002GAHNG03   08/22/00'                                      
         END                                                                    
