*          DATA SET SCEXAMPLE  AT LEVEL 037 AS OF 03/02/01                      
#SCRIPT EXAMPLE1                                                                
*                                                                               
*  THIS IS A TEST SCRIPT                                                        
*                                                                               
IAMS RMOR;                                                                      
USRS DDS1;SYSS CON;PRGS GEN;PWDS DDS;CT;                                        
NTHUNP 2;INPS EXC;TAB;INPS ADD;ENTER;       // ENTER EXCHANGE ADD               
*                                                                               
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
NTHUNP 6;INPS FT;TAB;INPS C;TAB;            // FT CLOSE                         
INPS ALL;TAB;INPS ALL;TAB;                  // ALL ALL                          
READ;SETOP 0;MVSO OK#;WRITE;                                                    
END;                                                                            
