*          DATA SET SCJDSREPC  AT LEVEL 003 AS OF 05/10/01                      
#SCRIPT JDSREPC                                                                 
USRS JDSREPC;SYSS REP;PRGS CFI;$CT;                                             
TSTOK;BE L2;ABEND;                                                              
.L2;                                                                            
READ;EXITNE;                                                                    
* MOVE SPECIAL DATA TO SCREEN                                                   
FU;TAB;INPI 5;ENTER;                                                            
EXIT;                                                                           
